[build-system]
requires = [
  "setuptools>=69",
  "setuptools-scm>=8",  # <-- required because you use [tool.setuptools_scm]
  "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
